// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJRNVKoizHt8C4G7tZO7pWPAXy6pS1mjk',
    appId: '1:898736739843:web:ca2d3439540b7e41326036',
    messagingSenderId: '898736739843',
    projectId: 'fir-crud-4d809',
    authDomain: 'fir-crud-4d809.firebaseapp.com',
    storageBucket: 'fir-crud-4d809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjV5sndwg3VtIGLQIP7Hs7fx54jS8Lqc',
    appId: '1:898736739843:android:dc3b6d1c6109df7e326036',
    messagingSenderId: '898736739843',
    projectId: 'fir-crud-4d809',
    storageBucket: 'fir-crud-4d809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8YYcwJJbdLPud7QlySUPY-u0EcsGNX0',
    appId: '1:898736739843:ios:4ce18c521c94ef3d326036',
    messagingSenderId: '898736739843',
    projectId: 'fir-crud-4d809',
    storageBucket: 'fir-crud-4d809.appspot.com',
    iosClientId: '898736739843-m1i6smg33mbevlm9s6s46r0rermrgpm6.apps.googleusercontent.com',
    iosBundleId: 'com.OpenCode.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN8YYcwJJbdLPud7QlySUPY-u0EcsGNX0',
    appId: '1:898736739843:ios:4ce18c521c94ef3d326036',
    messagingSenderId: '898736739843',
    projectId: 'fir-crud-4d809',
    storageBucket: 'fir-crud-4d809.appspot.com',
    iosClientId: '898736739843-m1i6smg33mbevlm9s6s46r0rermrgpm6.apps.googleusercontent.com',
    iosBundleId: 'com.OpenCode.flutterCrud',
  );
}
